@startuml
left to right direction
skinparam packageStyle rectangle

together {

    :Persona: as p
    :Empleado: as e
    :Timer: as t
    :Cliente: as c

    t -[hidden]l- c

    together {
        :Cliente VIP: as vc
        :Cliente Normal: as cn
        cn -[hidden]- vc
        vc -|> c
        cn -|> c
    }
    
}

rectangle Sistema_de_Librería {
    (Registrar Cliente) as registrar_cliente

    (Configurar Preferencias) as configurar_preferencias
    
    
    (Recomendar Libro) as recomendar
    (Agregar Amigo) as agregar_amigo
    (Eliminar Amigo) as eliminar_amigo
    (Seleccionar Amigo) as seleccionar_amigo
    agregar_amigo ..> seleccionar_amigo :<<includes>>
    eliminar_amigo ..> seleccionar_amigo :<<includes>>
    recomendar ..> seleccionar_amigo :<<includes>>

    (Buscar Libro) as buscar
    (Consultar Compras) as consultar_compras

    (Actualizar Stock) as actualizar_stock
    (Reservar Libro) as reservar
    reservar ..> actualizar_stock :<<includes>>
    together {
        (Comprar) as comprar 
        (Calcular Costo) as calcular_costo
    }

    (Cambiar Categoría Cliente) as cambiar_categoria

    (Cancelar Compra) as cancelar_compra
    (Cancelar Reserva) as cancelar_reserva


    (Ingresar Libro) as ingresar_libro
    (Notificar Cliente) as notificar
}

comprar <.. cambiar_categoria :<<extends>>
comprar ..> actualizar_stock :<<includes>>
comprar ..> calcular_costo :<<includes>>

cancelar_compra ..> actualizar_stock :<<includes>>

t --> cambiar_categoria
p --> registrar_cliente
e --> ingresar_libro
c --> configurar_preferencias
c --> recomendar
c --> agregar_amigo
c --> eliminar_amigo
c --> buscar
c --> comprar
c --> consultar_compras
c --> cancelar_compra
c --> reservar
c --> cancelar_reserva


ingresar_libro <.. notificar :<<extends>>


@enduml