@startuml


title c12 Comprar Libro - Flujo alternativo - Libros no disponibles

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s
        c <-- s : 
    deactivate s

deactivate c

@enduml

@startuml

title c12 Comprar Libro - Flujo alternativo - Libros no disponibles

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s

        c -> s : [len(libros) <= 0] terminar_compra()

        c <-- s
    deactivate s

deactivate c

@enduml

@startuml


title c12 Comprar Libro - Flujo alternativo - Libros no disponibles

actor Cliente as c
participant Sistema as s

c -> s : iniciar_compra(cliente)
activate c
    activate s
        c <-- s : libros = lista de libros
        c -> c : chequear_libros_disponibles(libros)

        c -> s : terminar_compra(cliente)

        c <-- s
    deactivate s

deactivate c

@enduml


@startuml


title c12 Comprar Libro

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s

        alt len(libros) > 0

            c -> s : seleccionar_libro(libro)
            s -> s : operacion1
            s -> s : operacion2
            s -> s : operación n
            note right
                operaciones que se ejecutan
                en el caso de uso.
                no lleva otra opción de else.
            end note

        end 

    deactivate s

deactivate c

@enduml