@startuml secuencia

actor actor
participant instanciaC as c <<ClassC>>
participant instanciaB as b <<ClassB>>

actor -> c : m1(p1)
activate c
    c -> b : obtener_datos()
    activate b
        return datos
    deactivate b
    actor <-- c : datos
deactivate c

@enduml

@startuml clases

class ClassC {
    propiedad1: int
    propiedad2: str

    void metodo1(): str
    void metodo2(parametro1:str): str
}

class ClassA {
    p1: int
    + void metodo1(): str
    - void metodo2(parametro1:str): str
}

ClassA <|-- ClassC

@enduml