@startuml

together {

    object Oferta {
        fecha_inicio: date
        fecha_fin: date
        descuento: int
    }

    object OfertaLanzamiento
    object OfertaTemporada
    object OfertaUltimosVolumenes
    object OfertaReedicion

    OfertaLanzamiento -u- Oferta
    OfertaReedicion -u- Oferta
    OfertaUltimosVolumenes -u- Oferta
    OfertaTemporada -u- Oferta

}


together {
    object Persona {
        nombre: str
        apellido: str
    }
    object Cliente {
        dirección: str
        país: str
        ciudad: str
        cp: str
        email: str
        teléfono: str
    }

    object Categoría
    object ClienteNormal
    object ClienteVIP
}

object Preferencias {
    notificar: bool
    género: str
    autor: str
    autores_comprados: bool
    generos_comprados: bool
}

together {
    object Libro {
        título: str
        idbn: str
    }
    object Digital {
        licencias: int
    }
    object Impreso {
        copias: int
    }
    object Genero {
        nombre: str
    }
    object Editorial {
        nombre: str
    }

}

together {

    object Compra {
        fecha: date
        costo: float
        cancelada: bool
    }
    object CompraStock {
    }
    object Reserva {
    }
    note bottom of Reserva: La reserva esta modelada como un tipo de compra
}

object Ingreso {
    fecha: date
    cantidad: int
    precio: float
}

object Recomendacion

object Notificación

object Libreria {
}

object Lanzamiento {
    fecha_inicio: date
    fecha_lanzamiento: date
    ejemplares: int
    limite_reservas: int
}

object Cuenta {
    credito: float
}


Libreria -> Cliente : clientes
Libreria -> Libro : libros
Libreria -> "(0..*)" Oferta : ofertas
Libreria -> Lanzamiento : lanzamientos

/'
object Inventario
object StockDigital {
    licencias: int
}
object StockFisico {
    copias: int
}

Inventario -u- StockDigital
StockDigital -u- "1" Digital : en_stock
Inventario -u- StockFisico
StockFisico -u- "1" Impreso : en_stock
'/

Cliente -d-> "1" Preferencias : pref
Cliente -d-> "1" Cuenta : cuenta


Compra -> "*" Libro : libro
Compra -d- CompraStock
Compra -d- Reserva
Compra "(0..*)" <- Cliente : compras

Libro --> "*" Persona : autores
Libro --> "*" Genero: genero
Libro --> "1" Editorial: editorial
Libro --> "*" Ingreso : ingresos

Persona -d-> Cliente
Cliente -d-> "1" Categoría : es
Categoría -d-> ClienteNormal
Categoría -d-> ClienteVIP

'Cliente ---> "*" Compra : realiza
Cliente -> "*" Cliente : amigo
Cliente -u-> "1" Recomendacion : recomienda
Recomendacion --> "1" Cliente : a
Recomendacion -l-> "1" Libro : libro


Libro -d- Digital
Libro -d- Impreso

Lanzamiento -d-> "1" Libro

Notificación -> "1" Cliente
Notificación -u-> "1" Lanzamiento

@enduml