@startuml

package "con stock dentro de libro" {
    object Libro {
        título: str
        idbn: str
        género: str
        editorial: str
        autor: str
    }
    object Digital {
        licencias: int
    }
    object Impreso {
        copias: int
    }

    object Ingreso {
    fecha: date
    cantidad: int
    precio: float
    }

    Libro -d- Digital
    Libro -d- Impreso

    Ingreso -d-> "1" Libro
}

package "stock fuera de libro" {
    note "me gusta mas esta\nmodelaría el tipo por herencia y con el libro por composición\ny el stock completamente fuera del libro" as n1
    object Libro1 {
        título: str
        idbn: str
        género: str
        editorial: str
        autor: str
    }
    object TipoLibro1
    object Digital1
    object Impreso1

    object Stock1 {
        cantidad: int
    }

    object Ingreso1 {
        fecha: date
        cantidad: int
        precio: float
    }

    Libro1 -> "1" TipoLibro1

    TipoLibro1 -d- Digital1
    TipoLibro1 -d- Impreso1

    Ingreso1 -d-> "1" Libro1

    Stock1 -> "1" Libro1
}



@enduml