@startuml metamodelo_clases_herencia


package Sistema {

    class Oferta {
        fecha_inicio: date
        fecha_fin: date
        descuento: int

        + calcular_descuento(compra:Compra)
        - aplicar_decuento(compra:Compra)
    }

    class OfertaLanzamiento {
    }

    class OfertaTemporada {
    }

    class OfertaUltimosVolumenes {
    }

    class OfertaReedicion {
    }

    Oferta <|-- OfertaLanzamiento
    Oferta <|-- OfertaReedicion
    Oferta <|-- OfertaUltimosVolumenes
    Oferta <|-- OfertaTemporada


}


package Metamodelo_Oferta {


    class ":Class" as c1 {
        name: String = "Oferta"
        isAbstract: Boolean = False
    }

    class ":PrimitiveType" as date_type {
        name: String = "date"
    }

    class ":Property" as a1 {
        name: String = "fecha_inicio"
        isDerived: Boolean = False
        isReadOnly: Boolean = False
        aggregation: Boolean = None
    }
    a1 *--> date_type : type

    class ":Property" as a2 {
        name: String = "fecha_fin"
        isDerived: Boolean = False
        isReadOnly: Boolean = False
        aggregation: Boolean = None
    }
    a2 *--> date_type : type


    class ":Property" as a3 {
        name: String = "descuento"
        isDerived: Boolean = False
        isReadOnly: Boolean = False
        aggregation: Boolean = None
    }

    class ":PrimitiveType" as a3t {
        name: String = "int"
    }
    a3 *--> a3t : type

    c1 *--> a1 : ownedAttribute
    c1 *--> a2 : ownedAttribute
    c1 *--> a3 : ownedAttribute

    class ":Class" as compra {
        name: String = "Compra"
        isAbstract: Boolean = False
    }

    class ":Operation" as m1 {
        name: String = "calcular_descuento"
        isQuery: Boolean = False
        visibility: VisibilityKind = Public
    }
    c1 *--> m1 : ownedOperation

    class ":Parameter" as m1_p1 {
        name: String = "compra"
        direction: ParameterDirectionKind = in
    }

    m1_p1 *--> compra : type
    m1 *--> m1_p1 : ownedParameter
    

    class ":Operation" as m2 {
        name: String = "aplicar_descuento"
        isQuery: Boolean = False
        visibility: VisibilityKind = Private
    }
    c1 *--> m2 : ownedOperation

    class ":Parameter" as m2_p1 {
        name: String = "compra"
        direction: ParameterDirectionLind = in
    }
    m2_p1 *--> compra : type
    m2 *--> m2_p1 : ownedParameter


}

package Metamodelo_Subclases {

    class ":Class" as o1 {
        name : String = "OfertaLanzamiento"
        isAbstract: Boolean = False
    }

    class ":Generalization" as g1 {

    }

    o1 *-- g1 : generalization
    g1 --> c1 : general



    class ":Class" as o2 {
        name : String = "OfertaTemporada"
        isAbstract: Boolean = False
    }

    class ":Generalization" as g2 {

    }

    o2 *-- g2 : generalization
    g2 --> c1 : general


    class ":Class" as o3 {
        name : String = "OfertaUltimosVolumenes"
        isAbstract: Boolean = False
    }

    class ":Generalization" as g3 {

    }

    o3 *-- g3 : generalization
    g3 --> c1 : general



    class ":Class" as o4 {
        name : String = "OfertaReedicion"
        isAbstract: Boolean = False
    }

    class ":Generalization" as g4 {

    }

    o4 *-- g4 : generalization
    g4 --> c1 : general


}


@enduml