@startuml
left to right direction
skinparam packageStyle rectangle

together {

    :Persona: as p
    :Empleado: as e
    :Timer: as t
    :Cliente: as c

    t -[hidden]l- c

    together {
        :Cliente VIP: as vc
        :Cliente Normal: as cn
        cn -[hidden]- vc
        vc -|> c
        cn -|> c
    }
    
}

rectangle Sistema_de_Librería {
    (c1 - Registrar Cliente) as c1
    (c2 - Configurar Preferencias) as c2

    (c3 - Recomendar Libro) as c3
    (c4 - Agregar Amigo) as c4
    (c5 - Eliminar Amigo) as c5
    (c6 - Seleccionar Amigo) as c6
    c4 ..> c6 :<<includes>>
    c5 ..> c6 :<<includes>>
    c3 ..> c6 :<<includes>>

    (c7 - Buscar Libro) as c7
    (c8 - Consultar Compras) as c8

    (c9 - Actualizar Stock) as c9
    (c10 - Actualizar Stock Pre-Venta) as c10
    (c11 - Reservar Libro) as c11
    together {
        (c12 - Comprar) as c12 
        (c13 - Calcular Costo) as c13
    }

    (c14 - Cambiar Categoría Cliente) as c14

    (c15 - Cancelar Compra) as c15
    (c16 - Cancelar Reserva) as c16


    (c17 - Ingresar Libro) as c17
    (c18 - Notificar Cliente) as c18
}

c12 <.. c14 :<<extends>>
c12 ..> c9 :<<includes>>
c12 ..> c13 :<<includes>>

c17 ..> c9 :<<includes>>

c15 ..> c9 :<<includes>>
c11 ..> c10 : <<includes>>
c16 ..> c10: <<includes>>

t --> c14
p --> c1
e --> c17
c --> c2
c --> c3
c --> c4
c --> c5
c --> c7
c --> c12
c --> c8
c --> c15
c --> c11
c --> c16


c17 <.. c18 :<<extends>>


@enduml