@startuml

class Libro {
    título
    autor
    editorial
    isbn
    géreno
}

class Cliente {
    nombre
    apellido
    dirección
    país
    ciudad
    codigo_postal
    calle
    número
    depto
    teléfono
    email
}

@enduml