@startuml

object Oferta {
    lazamiento: int
    temporada: int
    reedicion: int
    últimos_volúmenes: int
}


together {
    object Persona
    object Cliente {
        nombre: str
        apellido: str
        dirección: str
        país: str
        ciudad: str
        cp: str
        email: str
        teléfono: str
        crédito: float
    }
    object ClienteNormal
    object ClienteVIP
}

object Preferencias {
    notificar: bool
    género: str
    autor: str
    autores_comprados: bool
    generos_comprados: bool
}

together {
    object Libro {
        título: str
        idbn: str
        género: str
        editorial: str
    }
    object Digital {
        licencias: int
    }
    object Impreso {
        copias: int
    }
}


object Lanzamiento {
    fecha: date
    ejemplares: int
    limite_reservas: int
}

object Compra {
    fecha: date
    costo: float
    cancelada: bool
}
object CompraStock {
}
object Reserva {
}


object Ingreso {
    fecha: date
    cantidad: int
    precio: float
}


object Recomendacion

Compra - "1" Libro : libro
Compra -d- CompraStock
Compra -d- Reserva


Libro -- "*" Persona : autores
Persona -d- Cliente
Cliente -d- ClienteNormal
Cliente -d- ClienteVIP

Cliente -l- "*" Compra : realiza
Cliente -d- "1" Preferencias
Cliente - "*" Cliente : amigo
Cliente -d- "1" Recomendacion : recomienda
Recomendacion -u- "1" Cliente : a
Recomendacion -l- "1" Libro : libro

Libro -d- Digital
Libro -d- Impreso

Ingreso -d- "1" Libro
Lanzamiento -d- "1" Libro

@enduml