@startuml


title c12 Comprar Libro - Flujo alternativo - Libros no disponibles

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s
        s -> s : libros = buscar_libros_disponibles()
        return []
    deactivate s
deactivate c

@enduml