@startuml


title c12 Comprar Libro - Fujo alternativo - Libro no disponible

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s

        c -> s : seleccionar_libro(libro)

        s -> s : calcular_costo(libro)
        activate s
        deactivate s

        c <- s : obtener_informacion_pago()
        activate c
            c -> s : pago(info)
        deactivate c

        s -> s : actualizar_stock(libro)
        activate s
        deactivate s            


        c <-- s : stock_insuficiente

    deactivate s

deactivate c

@enduml