@startuml


title c12 Comprar Libro - Flujo alternativo - Crédito Insuficiente

actor Cliente as c
participant Sistema as s

c -> s : libros = iniciar_compra(cliente)
activate c
    activate s


        c -> s : seleccionar_libro(libro)

        s -> s : calcular_costo(libro)
        activate s
        deactivate s

        c <- s : obtener_informacion_pago()
        activate c
            c -> s : pago(info)
        deactivate c

        s -> s : actualizar_stock(libro)
        activate s
        deactivate s            


        s -> s : ok = descontar_costo(libro)
        activate s
        deactivate s


        s -> s : [not ok] cancelar_compra(libro)
        activate s
            s -> s : actualizar_stock(libro)
            c <-- s : crédito_insuficiente
        deactivate s

        
        

    deactivate s

deactivate c

@enduml